<?php

namespace AppBundle\Entity;

/**
 * ComercioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComercioRepository extends \Doctrine\ORM\EntityRepository
{
}
